### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by shealan** [meganabigaildavidson/b2-cloud-storage-service-provider#1]
Laravel refuses to recognise this package as valid, I assume because the actual code is in a branch.

> "The requested package insanekitty/b2-cloud-storage-service-provider could not be found in any version, there may be a typo in the package name." "The package is not available in a stable-enough version according to your minimum-stability setting"

**Comment by meganabigaildavidson** [comment]
Hi, That's correct. I'm really sorry be the package isn't even remotely finished yet; hence being in a develop branch. I've been so busy with other stuff. But will most likely jump back on it soon.
